### ISSUE TITLE
Script error or cyclic dependency

### ISSUE THREAD

**Issue by davidedg98** [crystal-bit/godot-game-template#11]
Class "Main" and "Game" couldn't be fully loaded.
![Cattura](https://user-images.githubusercontent.com/33494951/96892426-ecbfcd00-1489-11eb-92d6-c6491e7231f7.PNG)
![Cattura1](https://user-images.githubusercontent.com/33494951/96892560-0bbe5f00-148a-11eb-83bc-8b6191c5fb31.PNG)

**Comment by davcri** [comment]
Issue should be fixed now! Feel free to reopen this if needed! And thanks for reporting @davidedg98
