### ISSUE TITLE
Godot 3.3 update

### ISSUE THREAD

**Issue by davcri** [crystal-bit/godot-game-template#45]
- [x] Test project with Godot 3.3
- [x] Update Godot-CI (aBarichello)
- [x] Check godot-multi-builder (probably won't work with Godot 3.3 for Android export)

*UPDATE*: Android build actually works, but it's using an outdated Godot version

![](https://media.discordapp.net/attachments/713334956579094539/838454698335797258/Screenshot_20210502-183122.jpg?width=1416&height=637)

**Comment by Andrea-Miele** [comment]
Hi Crystal Bit! I'm working to enable the android support for godot 3.3

**Comment by davcri** [comment]
Hi @Andrea-Miele ! Thanks for your help, it's not an easy task so I appreciate your effort! Fell free to discuss anything on the Discord channel! Also you can ping me with @davcri here on GitHub :)

**Comment by Andrea-Miele** [comment]
Closed with #46 and #47
