### ISSUE TITLE
Transition.gd bug

### ISSUE THREAD

**Issue by eerbin13** [crystal-bit/godot-game-template#60]
Hi, I recently started using your game template. Frickin' awesome, btw. But I ran into this error, and it appears to be unrelated to my own code.
![transition bug](https://user-images.githubusercontent.com/16331/157927526-3a0044ac-23eb-4994-8b44-d99dd2bf10a5.png)

Any insight would be appreciated! Thanks again for the brilliant framework!

**Comment by eerbin13** [comment]
It also appears extremely intermittent. The same actions sometimes cause the error and sometimes do not. Leads me to believe it is a bug inside Godot itself.

**Comment by davcri** [comment]
Hi @eerbin13, thanks for reporting the issue! Which version of the template are you running? Unfortunately I cannot reproduce the bug on the current version.

However that error appears only if you call `fade_out` twice. Usually you should wait for the previous fade to finish before starting a new transition.

**Comment by eerbin13** [comment]
I think I may have found what was going on. I am rebuilding my project based on your fantastic template (and using what I've learned of Godot), and may have had a call to Game.change_scene() for a scene that doesn't exist (yet).

When it defaults back to the previous screen, the already connected error pops up, because, of course, the signal was already connected on this screen. 

I'm going to close this issue here. Thanks for entertaining my quandary.
