### ISSUE TITLE
Await `pre_start()` to be completed before triggering fade out transition

### ISSUE THREAD

**Issue by davcri** [crystal-bit/godot-game-template#66]
See https://github.com/crystal-bit/godot-game-template/commit/9aa7076fc53f98ca9ba50f34b78f6cac7457636b

**Comment by Iftahh** [comment]
I think this will crash if `pre_start` has no `yield` in it -   

to avoid a crash:

```
if instanced_scn.has_method("pre_start"):
		var coroutine_state = instanced_scn.pre_start(_params)
		if coroutine_state is GDScriptFunctionState && coroutine_state.is_valid():
			yield(coroutine_state, "completed")
```

**Comment by davcri** [comment]
You're right! Thanks for providing the fix! In the future feel free to open a pull request :)
