### ISSUE TITLE
Porting the template to godot 4

### ISSUE THREAD

**Issue by xShader1374** [crystal-bit/godot-game-template#76]
Would it be possible to port the template in godot 4? I use godot 4 and i'd like to be able to use the template too!

**Comment by davcri** [comment]
Hi @xShader1374, I'll consider porting the template to Godot 4 when there will be an official stable release. 
Probably I'll start a Godot 4 branch (like I did for [Defending Todot](https://github.com/crystal-bit/defending-todot/tree/godot4)) but it will be unofficial until Godot 4 gets a stable release.

**Comment by davcri** [comment]
An initial version with support for Godot 4 has been published in the [feature/godot4 branch](https://github.com/crystal-bit/godot-game-template/tree/feature/godot4)
